# Generated by Django 2.2.8 on 2020-10-28 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del expositor')),
                ('tema', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Título del tema')),
                ('enlaceMeet', models.URLField(blank=True, help_text='Escriba el enlace a Google Meet', max_length=250)),
                ('enlaceYouTube', models.URLField(blank=True, help_text='Escriba el enlace a YouTube', max_length=250)),
                ('ocultar_programa', models.BooleanField(default=False, verbose_name='No mostrar')),
            ],
            options={
                'verbose_name_plural': 'Programas',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Invitado',
        ),
    ]
