# Generated by Django 2.2.8 on 2020-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201028_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='FechaHora',
            field=models.DateTimeField(help_text='Fecha y hora de la charla', null=True, unique=True),
        ),
    ]
